package fpw.ren

import org.lwjgl.vulkan.VK10.*


enum class DescriptorType (val vk: Int)
{
	SAMPLER(VK_DESCRIPTOR_TYPE_SAMPLER),
	COMBINED_IMAGE_SAMPLER(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER),
	SAMPLED_IMAGE(VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE),
	STORAGE_IMAGE(VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
	UNIFORM_TEXEL_BUFFER(VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER),
	STORAGE_TEXEL_BUFFER(VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER),
	UNIFORM_BUFFER(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER),
	STORAGE_BUFFER(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
	UNIFORM_BUFFER_DYNAMIC(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC),
	STORAGE_BUFFER_DYNAMIC(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC),
	INPUT_ATTACHMENT(VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT),
}