package fpw.ren

import org.lwjgl.vulkan.VK10.*

enum class SamplerWrapping (val vkEnum: Int)
{
	REPEAT(VK_SAMPLER_ADDRESS_MODE_REPEAT),
	EXTEND(VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE),
	CLIP(VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER),
	MIRROR(VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT),
}