package fpw.ren.enums

import org.lwjgl.vulkan.VK10

enum class BlendFactor(val vk:Int)
{
	Zero(VK10.VK_BLEND_FACTOR_ZERO),
	One(VK10.VK_BLEND_FACTOR_ONE),

	SrcColor(VK10.VK_BLEND_FACTOR_SRC_COLOR),
	SrcAlpha(VK10.VK_BLEND_FACTOR_SRC_ALPHA),
	AntiSrcColor(VK10.VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR),
	AntiSrcAlpha(VK10.VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA),

	DstColor(VK10.VK_BLEND_FACTOR_DST_COLOR),
	DstAlpha(VK10.VK_BLEND_FACTOR_DST_ALPHA),
	AntiDstColor(VK10.VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR),
	AntiDstAlpha(VK10.VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA),

	ConstantColor(VK10.VK_BLEND_FACTOR_CONSTANT_COLOR),
	ConstantAlpha(VK10.VK_BLEND_FACTOR_CONSTANT_ALPHA),
	AntiConstantColor(VK10.VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR),
	AntiConstantAlpha(VK10.VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA),

	Src1Color(VK10.VK_BLEND_FACTOR_SRC1_COLOR),
	Src1Alpha(VK10.VK_BLEND_FACTOR_SRC1_ALPHA),
	AntiSrc1Color(VK10.VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR),
	AntiSrc1Alpha(VK10.VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA),

	SrcAlphaSaturate(VK10.VK_BLEND_FACTOR_SRC_ALPHA_SATURATE),
}