package fpw.ren.enums

import org.lwjgl.vulkan.VK10

enum class DescriptorType (val vk: Int)
{
	Sampler(VK10.VK_DESCRIPTOR_TYPE_SAMPLER),
	CombinedImageSampler(VK10.VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER),
	SampledImage(VK10.VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE),
	StorageImage(VK10.VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
	UniformTexelBuffer(VK10.VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER),
	StorageTexelBuffer(VK10.VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER),
	UniformBuffer(VK10.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER),
	StorageBuffer(VK10.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
	DynamicUniformBuffer(VK10.VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC),
	DynamicStorageBuffer(VK10.VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC),
	InputAttachment(VK10.VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT),
}